/**
 * Do not edit this file, this file is auto generate by script.
 * */

import {
  Attachment,
  AttachmentDTO,
  AttachmentParam,
  AuthToken,
  Author,
  BackupDTO,
  BaseCommentDTO,
  BaseCommentVO,
  BaseCommentWithParentVO,
  BaseMetaDTO,
  BasePostDetailDTO,
  BasePostMinimalDTO,
  BasePostSimpleDTO,
  BaseResponseboolean,
  BaseResponseobject,
  BaseResponsestring,
  CategoryDTO,
  CategoryParam,
  CategoryVO,
  EnvironmentDTO,
  Group,
  IndependentSheetDTO,
  InputStream,
  InstallParam,
  Item,
  JournalCommentParam,
  JournalCommentWithJournalVO,
  JournalDTO,
  JournalParam,
  JournalWithCmtCountDTO,
  LinkDTO,
  LinkParam,
  LogDTO,
  LoginParam,
  LoginPreCheckDTO,
  MailParam,
  MenuDTO,
  MenuParam,
  MenuVO,
  MultiFactorAuthParam,
  MultiFactorAuthVO,
  Option,
  OptionDTO,
  OptionParam,
  OptionSimpleDTO,
  Pageable,
  PageAttachmentDTO,
  PageBaseCommentVO,
  PageBaseCommentWithParentVO,
  PageBasePostSimpleDTO,
  PageJournalCommentWithJournalVO,
  PageJournalWithCmtCountDTO,
  PageLogDTO,
  PageOptionSimpleDTO,
  PagePhotoDTO,
  PagePostCommentWithPostVO,
  PageSheetCommentWithSheetVO,
  PageSheetListVO,
  PasswordParam,
  PhotoDTO,
  PhotoParam,
  Post,
  PostComment,
  PostCommentParam,
  PostCommentWithPostVO,
  PostContentParam,
  PostDetailVO,
  PostMarkdownParam,
  PostMetaParam,
  PostParam,
  ResetPasswordParam,
  Resource,
  SheetComment,
  SheetCommentParam,
  SheetCommentWithSheetVO,
  SheetDetailVO,
  SheetListVO,
  SheetMetaParam,
  SheetParam,
  Sort,
  StaticContentParam,
  StaticFile,
  StatisticDTO,
  StatisticWithUserDTO,
  TagDTO,
  TagParam,
  ThemeContentParam,
  ThemeFile,
  ThemeProperty,
  UserDTO,
  UserParam,
} from "./adminApiDefine";

import * as R from "../request";

export const api = {
  attachmentsGet(opt: {
    attachmentType:
      | "ALIOSS"
      | "BAIDUBOS"
      | "HUAWEIOBS"
      | "LOCAL"
      | "MINIO"
      | "QINIUOSS"
      | "SMMS"
      | "TENCENTCOS"
      | "UPOSS";
    keyword: string;
    mediaType: string;
    page: number;
    size: number;
    sort: Array<string>;
  }): Promise<PageAttachmentDTO> {
    return R.get("/api/admin/attachments", opt);
  },
  attachmentsRemove(opt: { ids: any }): Promise<Array<Attachment>> {
    return R.remove("/api/admin/attachments", opt);
  },
  attachmentsMedia_typesGet(): Promise<Array<string>> {
    return R.get("/api/admin/attachments/media_types");
  },
  attachmentsTypesGet(): Promise<
    Array<
      | "ALIOSS"
      | "BAIDUBOS"
      | "HUAWEIOBS"
      | "LOCAL"
      | "MINIO"
      | "QINIUOSS"
      | "SMMS"
      | "TENCENTCOS"
      | "UPOSS"
    >
  > {
    return R.get("/api/admin/attachments/types");
  },
  attachmentsUploadPost(opt: { file: any }): Promise<AttachmentDTO> {
    return R.post("/api/admin/attachments/upload", opt);
  },
  attachmentsUploadsPost(opt: {
    files: Array<any>;
  }): Promise<Array<AttachmentDTO>> {
    return R.post("/api/admin/attachments/uploads", opt);
  },
  attachmentsAttachmentIdPut(opt: {
    attachmentId: number;
    attachmentParam: any;
  }): Promise<AttachmentDTO> {
    return R.put("/api/admin/attachments/{attachmentId}", opt);
  },
  attachmentsIdGet(opt: { id: number }): Promise<AttachmentDTO> {
    return R.get("/api/admin/attachments/{id}", opt);
  },
  attachmentsIdRemove(opt: { id: number }): Promise<AttachmentDTO> {
    return R.remove("/api/admin/attachments/{id}", opt);
  },
  backupsDataGet(): Promise<Array<BackupDTO>> {
    return R.get("/api/admin/backups/data");
  },
  backupsDataPost(): Promise<BackupDTO> {
    return R.post("/api/admin/backups/data");
  },
  backupsDataRemove(opt: { filename: string }): Promise<void> {
    return R.remove("/api/admin/backups/data", opt);
  },
  backupsDataFileNameGet(opt: { fileName: string }): Promise<Resource> {
    return R.get("/api/admin/backups/data/{fileName}", opt);
  },
  backupsMarkdownExportGet(): Promise<Array<BackupDTO>> {
    return R.get("/api/admin/backups/markdown/export");
  },
  backupsMarkdownExportPost(opt: {
    postMarkdownParam: any;
  }): Promise<BackupDTO> {
    return R.post("/api/admin/backups/markdown/export", opt);
  },
  backupsMarkdownExportRemove(opt: { filename: string }): Promise<void> {
    return R.remove("/api/admin/backups/markdown/export", opt);
  },
  backupsMarkdownExportFileNameGet(opt: {
    fileName: string;
  }): Promise<Resource> {
    return R.get("/api/admin/backups/markdown/export/{fileName}", opt);
  },
  backupsMarkdownImportPost(opt: { file: any }): Promise<BasePostDetailDTO> {
    return R.post("/api/admin/backups/markdown/import", opt);
  },
  "backupsWork-dirGet"(): Promise<Array<BackupDTO>> {
    return R.get("/api/admin/backups/work-dir");
  },
  "backupsWork-dirPost"(): Promise<BackupDTO> {
    return R.post("/api/admin/backups/work-dir");
  },
  "backupsWork-dirRemove"(opt: { filename: string }): Promise<void> {
    return R.remove("/api/admin/backups/work-dir", opt);
  },
  "backupsWork-dirFileNameGet"(opt: { fileName: string }): Promise<Resource> {
    return R.get("/api/admin/backups/work-dir/{fileName}", opt);
  },
  categoriesGet(opt: {
    more: boolean;
    sort: Array<string>;
  }): Promise<Array<CategoryDTO>> {
    return R.get("/api/admin/categories", opt);
  },
  categoriesPost(opt: { categoryParam: any }): Promise<CategoryDTO> {
    return R.post("/api/admin/categories", opt);
  },
  categoriesTree_viewGet(opt: {
    sort: Array<string>;
  }): Promise<Array<CategoryVO>> {
    return R.get("/api/admin/categories/tree_view", opt);
  },
  categoriesCategoryIdGet(opt: { categoryId: number }): Promise<CategoryDTO> {
    return R.get("/api/admin/categories/{categoryId}", opt);
  },
  categoriesCategoryIdPut(opt: {
    categoryId: number;
    categoryParam: any;
  }): Promise<CategoryDTO> {
    return R.put("/api/admin/categories/{categoryId}", opt);
  },
  categoriesCategoryIdRemove(opt: { categoryId: number }): Promise<void> {
    return R.remove("/api/admin/categories/{categoryId}", opt);
  },
  countsGet(): Promise<StatisticDTO> {
    return R.get("/api/admin/counts");
  },
  environmentsGet(): Promise<EnvironmentDTO> {
    return R.get("/api/admin/environments");
  },
  haloLogfileGet(opt: { lines: number }): Promise<BaseResponsestring> {
    return R.get("/api/admin/halo/logfile", opt);
  },
  installationsPost(opt: { installParam: any }): Promise<BaseResponsestring> {
    return R.post("/api/admin/installations", opt);
  },
  is_installedGet(): Promise<boolean> {
    return R.get("/api/admin/is_installed");
  },
  journalsGet(opt: {
    keyword: string;
    page: number;
    size: number;
    sort: Array<string>;
    type: "INTIMATE" | "PUBLIC";
  }): Promise<PageJournalWithCmtCountDTO> {
    return R.get("/api/admin/journals", opt);
  },
  journalsPost(opt: { journalParam: any }): Promise<JournalDTO> {
    return R.post("/api/admin/journals", opt);
  },
  journalsCommentsGet(opt: {
    keyword: string;
    page: number;
    size: number;
    sort: Array<string>;
    status: "AUDITING" | "PUBLISHED" | "RECYCLE";
  }): Promise<PageJournalCommentWithJournalVO> {
    return R.get("/api/admin/journals/comments", opt);
  },
  journalsCommentsPost(opt: {
    journalCommentParam: any;
  }): Promise<BaseCommentDTO> {
    return R.post("/api/admin/journals/comments", opt);
  },
  journalsCommentsLatestGet(opt: {
    status: "AUDITING" | "PUBLISHED" | "RECYCLE";
    top: number;
  }): Promise<Array<JournalCommentWithJournalVO>> {
    return R.get("/api/admin/journals/comments/latest", opt);
  },
  journalsCommentsCommentIdRemove(opt: {
    commentId: number;
  }): Promise<BaseCommentDTO> {
    return R.remove("/api/admin/journals/comments/{commentId}", opt);
  },
  journalsCommentsCommentIdStatusStatusPut(opt: {
    commentId: number;
    status: "AUDITING" | "PUBLISHED" | "RECYCLE";
  }): Promise<BaseCommentDTO> {
    return R.put(
      "/api/admin/journals/comments/{commentId}/status/{status}",
      opt
    );
  },
  journalsCommentsJournalIdList_viewGet(opt: {
    journalId: number;
    page: number;
    sort: Array<string>;
  }): Promise<PageBaseCommentWithParentVO> {
    return R.get("/api/admin/journals/comments/{journalId}/list_view", opt);
  },
  journalsCommentsJournalIdTree_viewGet(opt: {
    journalId: number;
    page: number;
    sort: Array<string>;
  }): Promise<PageBaseCommentVO> {
    return R.get("/api/admin/journals/comments/{journalId}/tree_view", opt);
  },
  journalsLatestGet(opt: {
    top: number;
  }): Promise<Array<JournalWithCmtCountDTO>> {
    return R.get("/api/admin/journals/latest", opt);
  },
  journalsIdPut(opt: { id: number; journalParam: any }): Promise<JournalDTO> {
    return R.put("/api/admin/journals/{id}", opt);
  },
  journalsJournalIdRemove(opt: { journalId: number }): Promise<JournalDTO> {
    return R.remove("/api/admin/journals/{journalId}", opt);
  },
  linksGet(opt: { sort: Array<string> }): Promise<Array<LinkDTO>> {
    return R.get("/api/admin/links", opt);
  },
  linksPost(opt: { linkParam: any }): Promise<LinkDTO> {
    return R.post("/api/admin/links", opt);
  },
  linksTeamsGet(): Promise<Array<string>> {
    return R.get("/api/admin/links/teams");
  },
  linksIdGet(opt: { id: number }): Promise<LinkDTO> {
    return R.get("/api/admin/links/{id}", opt);
  },
  linksIdPut(opt: { id: number; linkParam: any }): Promise<LinkDTO> {
    return R.put("/api/admin/links/{id}", opt);
  },
  linksIdRemove(opt: { id: number }): Promise<void> {
    return R.remove("/api/admin/links/{id}", opt);
  },
  loginPost(opt: { loginParam: any }): Promise<AuthToken> {
    return R.post("/api/admin/login", opt);
  },
  loginPrecheckPost(opt: { loginParam: any }): Promise<LoginPreCheckDTO> {
    return R.post("/api/admin/login/precheck", opt);
  },
  logoutPost(): Promise<void> {
    return R.post("/api/admin/logout");
  },
  logsGet(opt: {
    page: number;
    size: number;
    sort: Array<string>;
  }): Promise<PageLogDTO> {
    return R.get("/api/admin/logs", opt);
  },
  logsClearGet(): Promise<void> {
    return R.get("/api/admin/logs/clear");
  },
  logsLatestGet(opt: { top: number }): Promise<Array<LogDTO>> {
    return R.get("/api/admin/logs/latest", opt);
  },
  mailsTestPost(opt: { mailParam: any }): Promise<BaseResponsestring> {
    return R.post("/api/admin/mails/test", opt);
  },
  mailsTestConnectionPost(): Promise<BaseResponsestring> {
    return R.post("/api/admin/mails/test/connection");
  },
  menusGet(opt: { sort: Array<string> }): Promise<Array<MenuDTO>> {
    return R.get("/api/admin/menus", opt);
  },
  menusPost(opt: { menuParam: any }): Promise<MenuDTO> {
    return R.post("/api/admin/menus", opt);
  },
  menusBatchPost(opt: { menuParams: any }): Promise<Array<MenuDTO>> {
    return R.post("/api/admin/menus/batch", opt);
  },
  menusBatchPut(opt: { menuParams: any }): Promise<Array<MenuDTO>> {
    return R.put("/api/admin/menus/batch", opt);
  },
  menusBatchRemove(opt: { menuIds: any }): Promise<Array<MenuDTO>> {
    return R.remove("/api/admin/menus/batch", opt);
  },
  menusTeamTree_viewGet(opt: {
    sort: Array<string>;
    team: string;
  }): Promise<Array<MenuVO>> {
    return R.get("/api/admin/menus/team/tree_view", opt);
  },
  menusTeamsGet(): Promise<Array<string>> {
    return R.get("/api/admin/menus/teams");
  },
  menusTree_viewGet(opt: { sort: Array<string> }): Promise<Array<MenuVO>> {
    return R.get("/api/admin/menus/tree_view", opt);
  },
  menusMenuIdGet(opt: { menuId: number }): Promise<MenuDTO> {
    return R.get("/api/admin/menus/{menuId}", opt);
  },
  menusMenuIdPut(opt: { menuId: number; menuParam: any }): Promise<MenuDTO> {
    return R.put("/api/admin/menus/{menuId}", opt);
  },
  menusMenuIdRemove(opt: { menuId: number }): Promise<MenuDTO> {
    return R.remove("/api/admin/menus/{menuId}", opt);
  },
  migrationsHaloPost(opt: { file: any }): Promise<void> {
    return R.post("/api/admin/migrations/halo", opt);
  },
  optionsGet(): Promise<Array<OptionDTO>> {
    return R.get("/api/admin/options");
  },
  optionsPost(opt: { optionParam: any }): Promise<void> {
    return R.post("/api/admin/options", opt);
  },
  optionsList_viewGet(opt: {
    keyword: string;
    page: number;
    size: number;
    sort: Array<string>;
    type: "CUSTOM" | "INTERNAL";
  }): Promise<PageOptionSimpleDTO> {
    return R.get("/api/admin/options/list_view", opt);
  },
  optionsMap_viewGet(): Promise<any> {
    return R.get("/api/admin/options/map_view");
  },
  optionsMap_viewKeysPost(opt: { keys: any }): Promise<any> {
    return R.post("/api/admin/options/map_view/keys", opt);
  },
  optionsMap_viewSavingPost(opt: { optionMap: any }): Promise<void> {
    return R.post("/api/admin/options/map_view/saving", opt);
  },
  optionsSavingPost(opt: { optionParams: any }): Promise<void> {
    return R.post("/api/admin/options/saving", opt);
  },
  optionsIdGet(opt: { id: number }): Promise<OptionSimpleDTO> {
    return R.get("/api/admin/options/{id}", opt);
  },
  optionsOptionIdPut(opt: {
    optionId: number;
    optionParam: any;
  }): Promise<void> {
    return R.put("/api/admin/options/{optionId}", opt);
  },
  optionsOptionIdRemove(opt: { optionId: number }): Promise<void> {
    return R.remove("/api/admin/options/{optionId}", opt);
  },
  passwordCodePost(opt: { param: any }): Promise<void> {
    return R.post("/api/admin/password/code", opt);
  },
  passwordResetPut(opt: { param: any }): Promise<void> {
    return R.put("/api/admin/password/reset", opt);
  },
  photosGet(opt: {
    keyword: string;
    page: number;
    size: number;
    sort: Array<string>;
    team: string;
  }): Promise<PagePhotoDTO> {
    return R.get("/api/admin/photos", opt);
  },
  photosPost(opt: { photoParam: any }): Promise<PhotoDTO> {
    return R.post("/api/admin/photos", opt);
  },
  photosLatestGet(opt: { sort: Array<string> }): Promise<Array<PhotoDTO>> {
    return R.get("/api/admin/photos/latest", opt);
  },
  photosTeamsGet(): Promise<Array<string>> {
    return R.get("/api/admin/photos/teams");
  },
  photosPhotoIdGet(opt: { photoId: number }): Promise<PhotoDTO> {
    return R.get("/api/admin/photos/{photoId}", opt);
  },
  photosPhotoIdPut(opt: {
    photoId: number;
    photoParam: any;
  }): Promise<PhotoDTO> {
    return R.put("/api/admin/photos/{photoId}", opt);
  },
  photosPhotoIdRemove(opt: { photoId: number }): Promise<void> {
    return R.remove("/api/admin/photos/{photoId}", opt);
  },
  postsGet(opt: {
    categoryId: number;
    keyword: string;
    more: boolean;
    page: number;
    size: number;
    sort: Array<string>;
    status: "DRAFT" | "INTIMATE" | "PUBLISHED" | "RECYCLE";
  }): Promise<PageBasePostSimpleDTO> {
    return R.get("/api/admin/posts", opt);
  },
  postsPost(opt: { autoSave: boolean; postParam: any }): Promise<PostDetailVO> {
    return R.post("/api/admin/posts", opt);
  },
  postsRemove(opt: { ids: any }): Promise<Array<Post>> {
    return R.remove("/api/admin/posts", opt);
  },
  postsCommentsGet(opt: {
    keyword: string;
    page: number;
    size: number;
    sort: Array<string>;
    status: "AUDITING" | "PUBLISHED" | "RECYCLE";
  }): Promise<PagePostCommentWithPostVO> {
    return R.get("/api/admin/posts/comments", opt);
  },
  postsCommentsPost(opt: { postCommentParam: any }): Promise<BaseCommentDTO> {
    return R.post("/api/admin/posts/comments", opt);
  },
  postsCommentsRemove(opt: { ids: any }): Promise<Array<PostComment>> {
    return R.remove("/api/admin/posts/comments", opt);
  },
  postsCommentsLatestGet(opt: {
    status: "AUDITING" | "PUBLISHED" | "RECYCLE";
    top: number;
  }): Promise<Array<PostCommentWithPostVO>> {
    return R.get("/api/admin/posts/comments/latest", opt);
  },
  postsCommentsStatusStatusPut(opt: {
    ids: any;
    status: "AUDITING" | "PUBLISHED" | "RECYCLE";
  }): Promise<Array<BaseCommentDTO>> {
    return R.put("/api/admin/posts/comments/status/{status}", opt);
  },
  postsCommentsCommentIdGet(opt: {
    commentId: number;
  }): Promise<PostCommentWithPostVO> {
    return R.get("/api/admin/posts/comments/{commentId}", opt);
  },
  postsCommentsCommentIdPut(opt: {
    commentId: number;
    commentParam: any;
  }): Promise<BaseCommentDTO> {
    return R.put("/api/admin/posts/comments/{commentId}", opt);
  },
  postsCommentsCommentIdRemove(opt: {
    commentId: number;
  }): Promise<BaseCommentDTO> {
    return R.remove("/api/admin/posts/comments/{commentId}", opt);
  },
  postsCommentsCommentIdStatusStatusPut(opt: {
    commentId: number;
    status: "AUDITING" | "PUBLISHED" | "RECYCLE";
  }): Promise<BaseCommentDTO> {
    return R.put("/api/admin/posts/comments/{commentId}/status/{status}", opt);
  },
  postsCommentsPostIdList_viewGet(opt: {
    page: number;
    postId: number;
    sort: Array<string>;
  }): Promise<PageBaseCommentWithParentVO> {
    return R.get("/api/admin/posts/comments/{postId}/list_view", opt);
  },
  postsCommentsPostIdTree_viewGet(opt: {
    page: number;
    postId: number;
    sort: Array<string>;
  }): Promise<PageBaseCommentVO> {
    return R.get("/api/admin/posts/comments/{postId}/tree_view", opt);
  },
  postsLatestGet(opt: { top: number }): Promise<Array<BasePostMinimalDTO>> {
    return R.get("/api/admin/posts/latest", opt);
  },
  postsPreviewPostIdGet(opt: { postId: number }): Promise<string> {
    return R.get("/api/admin/posts/preview/{postId}", opt);
  },
  postsStatusStatusGet(opt: {
    more: boolean;
    page: number;
    size: number;
    sort: Array<string>;
    status: "DRAFT" | "INTIMATE" | "PUBLISHED" | "RECYCLE";
  }): Promise<PageBasePostSimpleDTO> {
    return R.get("/api/admin/posts/status/{status}", opt);
  },
  postsStatusStatusPut(opt: {
    ids: any;
    status: "DRAFT" | "INTIMATE" | "PUBLISHED" | "RECYCLE";
  }): Promise<Array<Post>> {
    return R.put("/api/admin/posts/status/{status}", opt);
  },
  postsPostIdGet(opt: { postId: number }): Promise<PostDetailVO> {
    return R.get("/api/admin/posts/{postId}", opt);
  },
  postsPostIdPut(opt: {
    autoSave: boolean;
    postId: number;
    postParam: any;
  }): Promise<PostDetailVO> {
    return R.put("/api/admin/posts/{postId}", opt);
  },
  postsPostIdRemove(opt: { postId: number }): Promise<void> {
    return R.remove("/api/admin/posts/{postId}", opt);
  },
  postsPostIdLikesPut(opt: { postId: number }): Promise<void> {
    return R.put("/api/admin/posts/{postId}/likes", opt);
  },
  postsPostIdPreviewGet(opt: { postId: number }): Promise<string> {
    return R.get("/api/admin/posts/{postId}/preview", opt);
  },
  postsPostIdStatusDraftContentPut(opt: {
    contentParam: any;
    postId: number;
  }): Promise<BasePostDetailDTO> {
    return R.put("/api/admin/posts/{postId}/status/draft/content", opt);
  },
  postsPostIdStatusStatusPut(opt: {
    postId: number;
    status: "DRAFT" | "INTIMATE" | "PUBLISHED" | "RECYCLE";
  }): Promise<BasePostMinimalDTO> {
    return R.put("/api/admin/posts/{postId}/status/{status}", opt);
  },
  refreshRefreshTokenPost(opt: { refreshToken: string }): Promise<AuthToken> {
    return R.post("/api/admin/refresh/{refreshToken}", opt);
  },
  sheetsGet(opt: {
    page: number;
    size: number;
    sort: Array<string>;
  }): Promise<PageSheetListVO> {
    return R.get("/api/admin/sheets", opt);
  },
  sheetsPost(opt: {
    autoSave: boolean;
    sheetParam: any;
  }): Promise<SheetDetailVO> {
    return R.post("/api/admin/sheets", opt);
  },
  sheetsCommentsGet(opt: {
    keyword: string;
    page: number;
    size: number;
    sort: Array<string>;
    status: "AUDITING" | "PUBLISHED" | "RECYCLE";
  }): Promise<PageSheetCommentWithSheetVO> {
    return R.get("/api/admin/sheets/comments", opt);
  },
  sheetsCommentsPost(opt: { commentParam: any }): Promise<BaseCommentDTO> {
    return R.post("/api/admin/sheets/comments", opt);
  },
  sheetsCommentsRemove(opt: { ids: any }): Promise<Array<SheetComment>> {
    return R.remove("/api/admin/sheets/comments", opt);
  },
  sheetsCommentsLatestGet(opt: {
    status: "AUDITING" | "PUBLISHED" | "RECYCLE";
    top: number;
  }): Promise<Array<SheetCommentWithSheetVO>> {
    return R.get("/api/admin/sheets/comments/latest", opt);
  },
  sheetsCommentsStatusStatusPut(opt: {
    ids: any;
    status: "AUDITING" | "PUBLISHED" | "RECYCLE";
  }): Promise<Array<BaseCommentDTO>> {
    return R.put("/api/admin/sheets/comments/status/{status}", opt);
  },
  sheetsCommentsCommentIdGet(opt: {
    commentId: number;
  }): Promise<SheetCommentWithSheetVO> {
    return R.get("/api/admin/sheets/comments/{commentId}", opt);
  },
  sheetsCommentsCommentIdPut(opt: {
    commentId: number;
    commentParam: any;
  }): Promise<BaseCommentDTO> {
    return R.put("/api/admin/sheets/comments/{commentId}", opt);
  },
  sheetsCommentsCommentIdRemove(opt: {
    commentId: number;
  }): Promise<BaseCommentDTO> {
    return R.remove("/api/admin/sheets/comments/{commentId}", opt);
  },
  sheetsCommentsCommentIdStatusStatusPut(opt: {
    commentId: number;
    status: "AUDITING" | "PUBLISHED" | "RECYCLE";
  }): Promise<BaseCommentDTO> {
    return R.put("/api/admin/sheets/comments/{commentId}/status/{status}", opt);
  },
  sheetsCommentsSheetIdList_viewGet(opt: {
    page: number;
    sheetId: number;
    sort: Array<string>;
  }): Promise<PageBaseCommentWithParentVO> {
    return R.get("/api/admin/sheets/comments/{sheetId}/list_view", opt);
  },
  sheetsCommentsSheetIdTree_viewGet(opt: {
    page: number;
    sheetId: number;
    sort: Array<string>;
  }): Promise<PageBaseCommentVO> {
    return R.get("/api/admin/sheets/comments/{sheetId}/tree_view", opt);
  },
  sheetsIndependentGet(): Promise<Array<IndependentSheetDTO>> {
    return R.get("/api/admin/sheets/independent");
  },
  sheetsPreviewSheetIdGet(opt: { sheetId: number }): Promise<string> {
    return R.get("/api/admin/sheets/preview/{sheetId}", opt);
  },
  sheetsSheetIdGet(opt: { sheetId: number }): Promise<SheetDetailVO> {
    return R.get("/api/admin/sheets/{sheetId}", opt);
  },
  sheetsSheetIdPut(opt: {
    autoSave: boolean;
    sheetId: number;
    sheetParam: any;
  }): Promise<SheetDetailVO> {
    return R.put("/api/admin/sheets/{sheetId}", opt);
  },
  sheetsSheetIdRemove(opt: { sheetId: number }): Promise<SheetDetailVO> {
    return R.remove("/api/admin/sheets/{sheetId}", opt);
  },
  sheetsSheetIdStatusDraftContentPut(opt: {
    contentParam: any;
    sheetId: number;
  }): Promise<BasePostDetailDTO> {
    return R.put("/api/admin/sheets/{sheetId}/status/draft/content", opt);
  },
  sheetsSheetIdStatusPut(opt: {
    sheetId: number;
    status: "DRAFT" | "INTIMATE" | "PUBLISHED" | "RECYCLE";
  }): Promise<void> {
    return R.put("/api/admin/sheets/{sheetId}/{status}", opt);
  },
  staticsGet(): Promise<Array<StaticFile>> {
    return R.get("/api/admin/statics");
  },
  staticsPost(opt: { basePath: string; folderName: string }): Promise<void> {
    return R.post("/api/admin/statics", opt);
  },
  staticsRemove(opt: { path: string }): Promise<void> {
    return R.remove("/api/admin/statics", opt);
  },
  staticsFilesPut(opt: { param: any }): Promise<void> {
    return R.put("/api/admin/statics/files", opt);
  },
  staticsRenamePost(opt: { basePath: string; newName: string }): Promise<void> {
    return R.post("/api/admin/statics/rename", opt);
  },
  staticsUploadPost(opt: { basePath: string; file: any }): Promise<void> {
    return R.post("/api/admin/statics/upload", opt);
  },
  statisticsGet(): Promise<StatisticDTO> {
    return R.get("/api/admin/statistics");
  },
  statisticsUserGet(): Promise<StatisticWithUserDTO> {
    return R.get("/api/admin/statistics/user");
  },
  tagsGet(opt: { more: boolean; sort: Array<string> }): Promise<Array<TagDTO>> {
    return R.get("/api/admin/tags", opt);
  },
  tagsPost(opt: { tagParam: any }): Promise<TagDTO> {
    return R.post("/api/admin/tags", opt);
  },
  tagsTagIdGet(opt: { tagId: number }): Promise<TagDTO> {
    return R.get("/api/admin/tags/{tagId}", opt);
  },
  tagsTagIdPut(opt: { tagId: number; tagParam: any }): Promise<TagDTO> {
    return R.put("/api/admin/tags/{tagId}", opt);
  },
  tagsTagIdRemove(opt: { tagId: number }): Promise<TagDTO> {
    return R.remove("/api/admin/tags/{tagId}", opt);
  },
  themesGet(): Promise<Array<ThemeProperty>> {
    return R.get("/api/admin/themes");
  },
  themesActivationGet(): Promise<ThemeProperty> {
    return R.get("/api/admin/themes/activation");
  },
  themesActivationConfigurationsGet(): Promise<BaseResponseobject> {
    return R.get("/api/admin/themes/activation/configurations");
  },
  themesActivationFilesGet(): Promise<Array<ThemeFile>> {
    return R.get("/api/admin/themes/activation/files");
  },
  themesActivationSettingsGet(): Promise<any> {
    return R.get("/api/admin/themes/activation/settings");
  },
  themesActivationSettingsPost(opt: { settings: any }): Promise<void> {
    return R.post("/api/admin/themes/activation/settings", opt);
  },
  themesActivationTemplateCustomPostGet(): Promise<Array<string>> {
    return R.get("/api/admin/themes/activation/template/custom/post");
  },
  themesActivationTemplateCustomSheetGet(): Promise<Array<string>> {
    return R.get("/api/admin/themes/activation/template/custom/sheet");
  },
  themesActivationTemplateExistsGet(opt: {
    template: string;
  }): Promise<BaseResponseboolean> {
    return R.get("/api/admin/themes/activation/template/exists", opt);
  },
  themesFetchBranchGet(opt: {
    branch: string;
    uri: string;
  }): Promise<ThemeProperty> {
    return R.get("/api/admin/themes/fetchBranch", opt);
  },
  themesFetchLatestReleaseGet(opt: { uri: string }): Promise<ThemeProperty> {
    return R.get("/api/admin/themes/fetchLatestRelease", opt);
  },
  themesFetchingPost(opt: { uri: string }): Promise<ThemeProperty> {
    return R.post("/api/admin/themes/fetching", opt);
  },
  themesFetchingGitBranchesPost(opt: {
    uri: string;
  }): Promise<Array<ThemeProperty>> {
    return R.post("/api/admin/themes/fetching/git/branches", opt);
  },
  themesFetchingThemeIdPut(opt: { themeId: string }): Promise<ThemeProperty> {
    return R.put("/api/admin/themes/fetching/{themeId}", opt);
  },
  themesFetchingBranchesPost(opt: {
    uri: string;
  }): Promise<Array<ThemeProperty>> {
    return R.post("/api/admin/themes/fetchingBranches", opt);
  },
  themesFetchingReleaseGet(opt: {
    tag: string;
    uri: string;
  }): Promise<ThemeProperty> {
    return R.get("/api/admin/themes/fetchingRelease", opt);
  },
  themesFetchingReleasesPost(opt: {
    uri: string;
  }): Promise<Array<ThemeProperty>> {
    return R.post("/api/admin/themes/fetchingReleases", opt);
  },
  themesFilesContentGet(opt: { path: string }): Promise<BaseResponsestring> {
    return R.get("/api/admin/themes/files/content", opt);
  },
  themesFilesContentPut(opt: { param: any }): Promise<void> {
    return R.put("/api/admin/themes/files/content", opt);
  },
  themesReloadPost(): Promise<void> {
    return R.post("/api/admin/themes/reload");
  },
  themesUploadPost(opt: { file: any }): Promise<ThemeProperty> {
    return R.post("/api/admin/themes/upload", opt);
  },
  themesUploadThemeIdPut(opt: {
    file: any;
    themeId: string;
  }): Promise<ThemeProperty> {
    return R.put("/api/admin/themes/upload/{themeId}", opt);
  },
  themesThemeIdGet(opt: { themeId: string }): Promise<ThemeProperty> {
    return R.get("/api/admin/themes/{themeId}", opt);
  },
  themesThemeIdRemove(opt: {
    deleteSettings: boolean;
    themeId: string;
  }): Promise<void> {
    return R.remove("/api/admin/themes/{themeId}", opt);
  },
  themesThemeIdActivationPost(opt: {
    themeId: string;
  }): Promise<ThemeProperty> {
    return R.post("/api/admin/themes/{themeId}/activation", opt);
  },
  themesThemeIdConfigurationsGet(opt: {
    themeId: string;
  }): Promise<Array<Group>> {
    return R.get("/api/admin/themes/{themeId}/configurations", opt);
  },
  themesThemeIdFilesGet(opt: { themeId: string }): Promise<Array<ThemeFile>> {
    return R.get("/api/admin/themes/{themeId}/files", opt);
  },
  themesThemeIdFilesContentGet(opt: {
    path: string;
    themeId: string;
  }): Promise<BaseResponsestring> {
    return R.get("/api/admin/themes/{themeId}/files/content", opt);
  },
  themesThemeIdFilesContentPut(opt: {
    param: any;
    themeId: string;
  }): Promise<void> {
    return R.put("/api/admin/themes/{themeId}/files/content", opt);
  },
  themesThemeIdSettingsGet(opt: { themeId: string }): Promise<any> {
    return R.get("/api/admin/themes/{themeId}/settings", opt);
  },
  themesThemeIdSettingsPost(opt: {
    settings: any;
    themeId: string;
  }): Promise<void> {
    return R.post("/api/admin/themes/{themeId}/settings", opt);
  },
  usersMfaGeneratePut(opt: {
    multiFactorAuthParam: any;
  }): Promise<MultiFactorAuthVO> {
    return R.put("/api/admin/users/mfa/generate", opt);
  },
  usersMfaUpdatePut(opt: {
    multiFactorAuthParam: any;
  }): Promise<MultiFactorAuthVO> {
    return R.put("/api/admin/users/mfa/update", opt);
  },
  usersProfilesGet(): Promise<UserDTO> {
    return R.get("/api/admin/users/profiles");
  },
  usersProfilesPut(opt: { userParam: any }): Promise<UserDTO> {
    return R.put("/api/admin/users/profiles", opt);
  },
  usersProfilesPasswordPut(opt: {
    passwordParam: any;
  }): Promise<BaseResponsestring> {
    return R.put("/api/admin/users/profiles/password", opt);
  },
};
