/* eslint-disable  */
// @ts-nocheck
/**
 * Do not edit this file, this file is auto generate by script.
 * */

import {
  ArchiveMonthVO,
  ArchiveYearVO,
  Author,
  BaseCommentDTO,
  BaseCommentVO,
  BaseCommentWithParentVO,
  BaseMetaDTO,
  BasePostSimpleDTO,
  BaseResponseOfobject,
  CategoryDTO,
  CommentWithHasChildrenVO,
  CustomizedPageOfBaseCommentVO,
  CustomizedPageOfBaseCommentWithParentVO,
  CustomizedPageOfBasePostSimpleDTO,
  CustomizedPageOfCommentWithHasChildrenVO,
  CustomizedPageOfJournalWithCmtCountDTO,
  CustomizedPageOfPhotoDTO,
  CustomizedPageOfPostListVO,
  CustomizedPageOfSheetListVO,
  JournalCommentParam,
  JournalDTO,
  JournalWithCmtCountDTO,
  LinkDTO,
  LinkTeamVO,
  MenuDTO,
  MenuVO,
  OptionDTO,
  PhotoDTO,
  PostCommentParam,
  PostDetailVO,
  PostListVO,
  SheetCommentParam,
  SheetDetailVO,
  SheetListVO,
  StatisticDTO,
  StatisticWithUserDTO,
  TagDTO,
  ThemeProperty,
  UserDTO,
} from "./contentApiDefine";

export const apiInfo = {
  version: "1.4.5",
  authKey: "API-Authorization",
};

// @ts-nocheck
import axios, { AxiosInstance, AxiosRequestConfig } from "axios";

interface IConfig {
  target: string;
  accessKey: string;
  axios: AxiosInstance;
}

export const configs: IConfig = {
  target: "",
  accessKey: "",
  axios: null,
};

export function axiosRequestInterceptor(conf: AxiosRequestConfig) {
  if (configs.accessKey) {
    // apiInfo generate by core.ts
    conf.headers[apiInfo.authKey] = configs.accessKey;
  }

  conf.url = conf.url.replace(/\{\w+\}/g, (name) => {
    return conf.params[name.slice(1, name.length - 1)];
  });

  return conf;
}

export function initConfig(opt: Partial<IConfig>) {
  Object.assign(configs, opt);

  configs.axios = axios.create({
    baseURL: configs.target,
  });

  configs.axios.interceptors.request.use(axiosRequestInterceptor);
}

function decodeResponseData(data: any) {
  return data.data ? data.data : data;
}

async function get(path: string, data?: any) {
  const res = await configs.axios.get(path, {
    params: data,
  });

  return decodeResponseData(res.data);
}

async function post(path: string, data?: any) {
  const res = await configs.axios.post(path, data);

  return decodeResponseData(res.data);
}

async function put(path: string, data?: any) {
  const res = await configs.axios.put(path, data);

  return decodeResponseData(res.data);
}

async function remove(path: string, data?: any) {
  const res = await configs.axios.delete(path, { params: data });

  return decodeResponseData(res.data);
}

/**
 * listMonthArchives
 */
export function archivesMonthsGet(): Promise<Array<ArchiveMonthVO>> {
  return get("/api/content/archives/months");
}

/**
 * listYearArchives
 */
export function archivesYearsGet(): Promise<Array<ArchiveYearVO>> {
  return get("/api/content/archives/years");
}

/**
 * Lists categories
 */
export function categoriesGet(opt: {
  /**
   *
   */
  sort?: any;

  /**
   * more
   */
  more?: any;
}): Promise<Array<CategoryDTO>> {
  return get("/api/content/categories", opt);
}

/**
 * Lists posts by category slug
 */
export function categoriesSlugPostsGet(opt: {
  /**
   *
   */
  page?: any;

  /**
   *
   */
  size?: any;

  /**
   * slug
   */
  slug: any;

  /**
   *
   */
  sort?: any;

  /**
   * password
   */
  password?: any;
}): Promise<CustomizedPageOfPostListVO> {
  return get("/api/content/categories/{slug}/posts", opt);
}

/**
 * Lists journals
 */
export function journalsGet(opt: {
  /**
   *
   */
  page?: any;

  /**
   *
   */
  size?: any;

  /**
   *
   */
  sort?: any;
}): Promise<CustomizedPageOfJournalWithCmtCountDTO> {
  return get("/api/content/journals", opt);
}

/**
 * Comments a post
 */
export function journalsCommentsPost(): Promise<BaseCommentDTO> {
  return post("/api/content/journals/comments");
}

/**
 * Likes a journal
 */
export function journalsIdLikesPost(opt: {
  /**
   * id
   */
  id: any;
}): Promise<void> {
  return post("/api/content/journals/{id}/likes", opt);
}

/**
 * Gets a journal detail
 */
export function journalsJournalIdGet(opt: {
  /**
   * journalId
   */
  journalId: any;
}): Promise<JournalDTO> {
  return get("/api/content/journals/{journalId}", opt);
}

/**
 * Lists comment with list view
 */
export function journalsJournalIdCommentsList_viewGet(opt: {
  /**
   * journalId
   */
  journalId: any;

  /**
   *
   */
  sort?: any;

  /**
   * page
   */
  page?: any;
}): Promise<CustomizedPageOfBaseCommentWithParentVO> {
  return get("/api/content/journals/{journalId}/comments/list_view", opt);
}

/**
 * listTopComments
 */
export function journalsJournalIdCommentsTop_viewGet(opt: {
  /**
   * journalId
   */
  journalId: any;

  /**
   *
   */
  sort?: any;

  /**
   * page
   */
  page?: any;
}): Promise<CustomizedPageOfCommentWithHasChildrenVO> {
  return get("/api/content/journals/{journalId}/comments/top_view", opt);
}

/**
 * Lists comments with tree view
 */
export function journalsJournalIdCommentsTree_viewGet(opt: {
  /**
   * journalId
   */
  journalId: any;

  /**
   *
   */
  sort?: any;

  /**
   * page
   */
  page?: any;
}): Promise<CustomizedPageOfBaseCommentVO> {
  return get("/api/content/journals/{journalId}/comments/tree_view", opt);
}

/**
 * listChildrenBy
 */
export function journalsJournalIdCommentsCommentParentIdChildrenGet(opt: {
  /**
   * journalId
   */
  journalId: any;

  /**
   *
   */
  sort?: any;

  /**
   * commentParentId
   */
  commentParentId: any;
}): Promise<Array<BaseCommentDTO>> {
  return get(
    "/api/content/journals/{journalId}/comments/{commentParentId}/children",
    opt
  );
}

/**
 * List all links
 */
export function linksGet(opt: {
  /**
   *
   */
  sort?: any;
}): Promise<Array<LinkDTO>> {
  return get("/api/content/links", opt);
}

/**
 * List all links with team view
 */
export function linksTeam_viewGet(opt: {
  /**
   *
   */
  sort?: any;
}): Promise<Array<LinkTeamVO>> {
  return get("/api/content/links/team_view", opt);
}

/**
 * Lists all menus
 */
export function menusGet(opt: {
  /**
   *
   */
  sort?: any;
}): Promise<Array<MenuDTO>> {
  return get("/api/content/menus", opt);
}

/**
 * Lists menus with tree view
 */
export function menusTree_viewGet(opt: {
  /**
   *
   */
  sort?: any;
}): Promise<Array<MenuVO>> {
  return get("/api/content/menus/tree_view", opt);
}

/**
 * Options for comment
 */
export function optionsCommentGet(): Promise<any> {
  return get("/api/content/options/comment");
}

/**
 * Gets option value by option key
 */
export function optionsKeysKeyGet(opt: {
  /**
   * key
   */
  key: any;
}): Promise<BaseResponseOfobject> {
  return get("/api/content/options/keys/{key}", opt);
}

/**
 * Lists all options with list view
 */
export function optionsList_viewGet(): Promise<Array<OptionDTO>> {
  return get("/api/content/options/list_view");
}

/**
 * Lists options with map view
 */
export function optionsMap_viewGet(opt: {
  /**
   * key
   */
  key?: any;
}): Promise<any> {
  return get("/api/content/options/map_view", opt);
}

/**
 * pageBy
 */
export function photosGet(opt: {
  /**
   *
   */
  keyword?: any;

  /**
   *
   */
  page?: any;

  /**
   *
   */
  size?: any;

  /**
   *
   */
  sort?: any;

  /**
   *
   */
  team?: any;
}): Promise<CustomizedPageOfPhotoDTO> {
  return get("/api/content/photos", opt);
}

/**
 * listPhotos
 */
export function photosLatestGet(opt: {
  /**
   *
   */
  sort?: any;
}): Promise<Array<PhotoDTO>> {
  return get("/api/content/photos/latest", opt);
}

/**
 * Lists posts
 */
export function postsGet(opt: {
  /**
   *
   */
  page?: any;

  /**
   *
   */
  size?: any;

  /**
   *
   */
  sort?: any;
}): Promise<CustomizedPageOfPostListVO> {
  return get("/api/content/posts", opt);
}

/**
 * Comments a post
 */
export function postsCommentsPost(): Promise<BaseCommentDTO> {
  return post("/api/content/posts/comments");
}

/**
 * Lists posts by keyword
 */
export function postsSearchPost(opt: {
  /**
   * keyword
   */
  keyword: any;

  /**
   *
   */
  page?: any;

  /**
   *
   */
  size?: any;

  /**
   *
   */
  sort?: any;
}): Promise<CustomizedPageOfBasePostSimpleDTO> {
  return post("/api/content/posts/search", opt);
}

/**
 * Gets a post
 */
export function postsSlugGet(opt: {
  /**
   * slug
   */
  slug: any;

  /**
   * formatDisabled
   */
  formatDisabled?: any;

  /**
   * sourceDisabled
   */
  sourceDisabled?: any;
}): Promise<PostDetailVO> {
  return get("/api/content/posts/slug", opt);
}

/**
 * Gets a post
 */
export function postsPostIdGet(opt: {
  /**
   * postId
   */
  postId: any;

  /**
   * formatDisabled
   */
  formatDisabled?: any;

  /**
   * sourceDisabled
   */
  sourceDisabled?: any;
}): Promise<PostDetailVO> {
  return get("/api/content/posts/{postId}", opt);
}

/**
 * Lists comment with list view
 */
export function postsPostIdCommentsList_viewGet(opt: {
  /**
   * postId
   */
  postId: any;

  /**
   *
   */
  sort?: any;

  /**
   * page
   */
  page?: any;
}): Promise<CustomizedPageOfBaseCommentWithParentVO> {
  return get("/api/content/posts/{postId}/comments/list_view", opt);
}

/**
 * listTopComments
 */
export function postsPostIdCommentsTop_viewGet(opt: {
  /**
   * postId
   */
  postId: any;

  /**
   *
   */
  sort?: any;

  /**
   * page
   */
  page?: any;
}): Promise<CustomizedPageOfCommentWithHasChildrenVO> {
  return get("/api/content/posts/{postId}/comments/top_view", opt);
}

/**
 * Lists comments with tree view
 */
export function postsPostIdCommentsTree_viewGet(opt: {
  /**
   * postId
   */
  postId: any;

  /**
   *
   */
  sort?: any;

  /**
   * page
   */
  page?: any;
}): Promise<CustomizedPageOfBaseCommentVO> {
  return get("/api/content/posts/{postId}/comments/tree_view", opt);
}

/**
 * listChildrenBy
 */
export function postsPostIdCommentsCommentParentIdChildrenGet(opt: {
  /**
   * postId
   */
  postId: any;

  /**
   *
   */
  sort?: any;

  /**
   * commentParentId
   */
  commentParentId: any;
}): Promise<Array<BaseCommentDTO>> {
  return get(
    "/api/content/posts/{postId}/comments/{commentParentId}/children",
    opt
  );
}

/**
 * Likes a post
 */
export function postsPostIdLikesPost(opt: {
  /**
   * postId
   */
  postId: any;
}): Promise<void> {
  return post("/api/content/posts/{postId}/likes", opt);
}

/**
 * Gets next post by current post id.
 */
export function postsPostIdNextGet(opt: {
  /**
   * postId
   */
  postId: any;
}): Promise<PostDetailVO> {
  return get("/api/content/posts/{postId}/next", opt);
}

/**
 * Gets previous post by current post id.
 */
export function postsPostIdPrevGet(opt: {
  /**
   * postId
   */
  postId: any;
}): Promise<PostDetailVO> {
  return get("/api/content/posts/{postId}/prev", opt);
}

/**
 * Lists sheets
 */
export function sheetsGet(opt: {
  /**
   *
   */
  page?: any;

  /**
   *
   */
  size?: any;

  /**
   *
   */
  sort?: any;
}): Promise<CustomizedPageOfSheetListVO> {
  return get("/api/content/sheets", opt);
}

/**
 * Comments a post
 */
export function sheetsCommentsPost(): Promise<BaseCommentDTO> {
  return post("/api/content/sheets/comments");
}

/**
 * Gets a sheet by slug
 */
export function sheetsSlugGet(opt: {
  /**
   * slug
   */
  slug: any;

  /**
   * formatDisabled
   */
  formatDisabled?: any;

  /**
   * sourceDisabled
   */
  sourceDisabled?: any;
}): Promise<SheetDetailVO> {
  return get("/api/content/sheets/slug", opt);
}

/**
 * Gets a sheet
 */
export function sheetsSheetIdGet(opt: {
  /**
   * sheetId
   */
  sheetId: any;

  /**
   * formatDisabled
   */
  formatDisabled?: any;

  /**
   * sourceDisabled
   */
  sourceDisabled?: any;
}): Promise<SheetDetailVO> {
  return get("/api/content/sheets/{sheetId}", opt);
}

/**
 * Lists comment with list view
 */
export function sheetsSheetIdCommentsList_viewGet(opt: {
  /**
   * sheetId
   */
  sheetId: any;

  /**
   *
   */
  sort?: any;

  /**
   * page
   */
  page?: any;
}): Promise<CustomizedPageOfBaseCommentWithParentVO> {
  return get("/api/content/sheets/{sheetId}/comments/list_view", opt);
}

/**
 * listTopComments
 */
export function sheetsSheetIdCommentsTop_viewGet(opt: {
  /**
   * sheetId
   */
  sheetId: any;

  /**
   *
   */
  sort?: any;

  /**
   * page
   */
  page?: any;
}): Promise<CustomizedPageOfCommentWithHasChildrenVO> {
  return get("/api/content/sheets/{sheetId}/comments/top_view", opt);
}

/**
 * Lists comments with tree view
 */
export function sheetsSheetIdCommentsTree_viewGet(opt: {
  /**
   * sheetId
   */
  sheetId: any;

  /**
   *
   */
  sort?: any;

  /**
   * page
   */
  page?: any;
}): Promise<CustomizedPageOfBaseCommentVO> {
  return get("/api/content/sheets/{sheetId}/comments/tree_view", opt);
}

/**
 * listChildrenBy
 */
export function sheetsSheetIdCommentsCommentParentIdChildrenGet(opt: {
  /**
   * sheetId
   */
  sheetId: any;

  /**
   *
   */
  sort?: any;

  /**
   * commentParentId
   */
  commentParentId: any;
}): Promise<Array<BaseCommentDTO>> {
  return get(
    "/api/content/sheets/{sheetId}/comments/{commentParentId}/children",
    opt
  );
}

/**
 * Gets blog statistics.
 */
export function statisticsGet(): Promise<StatisticDTO> {
  return get("/api/content/statistics");
}

/**
 * Gets blog statistics with user
 */
export function statisticsUserGet(): Promise<StatisticWithUserDTO> {
  return get("/api/content/statistics/user");
}

/**
 * Lists tags
 */
export function tagsGet(opt: {
  /**
   *
   */
  sort?: any;

  /**
   * If the param is true, post count of tag will be returned
   */
  more?: any;
}): Promise<Array<TagDTO>> {
  return get("/api/content/tags", opt);
}

/**
 * Lists posts by tag slug
 */
export function tagsSlugPostsGet(opt: {
  /**
   *
   */
  page?: any;

  /**
   *
   */
  size?: any;

  /**
   * slug
   */
  slug: any;

  /**
   *
   */
  sort?: any;
}): Promise<CustomizedPageOfPostListVO> {
  return get("/api/content/tags/{slug}/posts", opt);
}

/**
 * Gets activated theme property
 */
export function themesActivationGet(): Promise<ThemeProperty> {
  return get("/api/content/themes/activation");
}

/**
 * Lists activated theme settings
 */
export function themesActivationSettingsGet(): Promise<any> {
  return get("/api/content/themes/activation/settings");
}

/**
 * Gets blogger profile
 */
export function usersProfileGet(): Promise<UserDTO> {
  return get("/api/content/users/profile");
}
